# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lattekafe
email: hojin.joseph.choi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  눈으로만 공부하다가 까먹어서 기억하려 만든 블로그
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lattekafe.com" # the base hostname & protocol for your site
twitter_username: lattekafee
github_username: lattekafe  


# Build settings
markdown: kramdown

#disqus
disqus: lattekafe
